# Generated by Django 5.2 on 2025-04-07 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('imageUrl', models.URLField()),
                ('url', models.URLField()),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('cardNumber', models.CharField(max_length=8)),
                ('effect', models.TextField()),
                ('colorOne', models.CharField(max_length=6)),
                ('colorTwo', models.CharField(max_length=6)),
                ('subtype', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('attribute', models.CharField(max_length=10)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rarity', models.CharField(max_length=3)),
                ('art', models.CharField(max_length=8)),
                ('cost', models.IntegerField()),
                ('power', models.IntegerField()),
                ('counter', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('imageUrl', models.URLField()),
                ('url', models.URLField()),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('cardNumber', models.CharField(max_length=8)),
                ('effect', models.TextField()),
                ('colorOne', models.CharField(max_length=6)),
                ('colorTwo', models.CharField(max_length=6)),
                ('subtype', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('attribute', models.CharField(max_length=10)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rarity', models.CharField(max_length=3)),
                ('art', models.CharField(max_length=8)),
                ('cost', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('imageUrl', models.URLField()),
                ('url', models.URLField()),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('cardNumber', models.CharField(max_length=8)),
                ('effect', models.TextField()),
                ('colorOne', models.CharField(max_length=6)),
                ('colorTwo', models.CharField(max_length=6)),
                ('subtype', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('attribute', models.CharField(max_length=10)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rarity', models.CharField(max_length=3)),
                ('art', models.CharField(max_length=8)),
                ('life', models.IntegerField()),
                ('power', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('imageUrl', models.URLField()),
                ('url', models.URLField()),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('cardNumber', models.CharField(max_length=8)),
                ('effect', models.TextField()),
                ('colorOne', models.CharField(max_length=6)),
                ('colorTwo', models.CharField(max_length=6)),
                ('subtype', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('attribute', models.CharField(max_length=10)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rarity', models.CharField(max_length=3)),
                ('art', models.CharField(max_length=8)),
                ('cost', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
