# Generated by Django 5.2 on 2025-04-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='attribute',
        ),
    ]
