# Generated by Django 5.2 on 2025-04-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0003_remove_character_id_remove_event_id_remove_leader_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pricehistory',
            name='database_pr_content_a45df8_idx',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='content_type',
            new_name='card_type',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='object_id',
            new_name='product_id',
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['card_type', 'product_id'], name='database_pr_card_ty_71d990_idx'),
        ),
    ]
