# Generated by Django 5.2 on 2025-04-11 05:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_rename_cardnumber_character_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='color_two',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='color_two',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='leader',
            name='color_two',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stage',
            name='color_two',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None),
        ),
    ]
