# Generated by Django 5.2 on 2025-04-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_character_attribute_alter_leader_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='effect',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='effect',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='effect',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='effect',
            field=models.TextField(null=True),
        ),
    ]
