# Generated by Django 5.2 on 2025-04-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_character_effect_alter_event_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='card_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='card_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='leader',
            name='card_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stage',
            name='card_number',
            field=models.CharField(max_length=10),
        ),
    ]
