# Generated by Django 5.2 on 2025-04-14 05:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_character_art_alter_event_art_alter_leader_art_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('card_number', models.CharField(max_length=10)),
                ('effect', models.TextField(null=True)),
                ('color_one', models.CharField(max_length=6)),
                ('color_two', models.CharField(max_length=6, null=True)),
                ('subtype', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rarity', models.CharField(max_length=3)),
                ('art', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
