# Generated by Django 5.2 on 2025-04-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_don'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='don',
            name='rarity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='rarity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='leader',
            name='rarity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stage',
            name='rarity',
            field=models.CharField(max_length=10),
        ),
    ]
